### ISSUE TITLE
strictness: lock-down versions in dependencies

### ISSUE THREAD

**Issue by jokeyrhyme** [HenrikJoreteg/fixpack#13] opened 2015-11-23 00:19 UTC
I've recently read suggestions from multiple places to put exact versions in package.json:
- http://blog.heroku.com/archives/2015/11/10/node-habits-2016#2-use-a-smart-npmrc

If you were inclined to agree with this, do you think `fixpack` should lock down versions in the "dependencies" section as part of its operation? Should this be the default behaviour, or maybe an option?

I'm inclined to leave "peerDependencies" alone, as using exact versions there sounds like it would cause all sorts of chaos.

I'm inclined to leave "devDependencies" alone, as strictness there seems less helpful (in my opinion), but I could easily be persuaded that strictness there is just as important as with "dependencies".

Is this a bad idea, or beyond the scope for `fixpack`?
Would you like to see a PR (or separate PRs) for this?
- [ ] for "dependencies" versions like "~1.2.3" or "^1.2.3", automatically remove the "~" or the "^"
- [ ] for remaining inexact "dependencies" versions, exit code 1 with report

**Comment by jokeyrhyme** [comment] 2016-08-05 12:33
My latest opinion on dependencies (ignoring devDeps and peerDeps for now) is that:

- version strictness (i.e. exact version 1.2.3) is good for dependency graph leaves, e.g. apps, globally-installed CLIs, etc

    - we need to be able to control and debug what the end-user experiences

- version inclusiveness (i.e. ^1.2.3) is fine for dependency graph roots and branches, e.g. micro libraries and frameworks, reusable UI components, etc

    - having strict version control here makes these far less convenient to use and maintain

**Comment by NodeGuy** [comment] 2017-01-04 19:03
I would like an option to require exact versions for all dependencies.  I think the world is moving in this direction with https://reproducible-builds.org/.

**Comment by jokeyrhyme** [comment] 2017-01-04 21:28
Note that [`yarn`](https://yarnpkg.com/) achieves reproducibility without caring about how strict or loose the versions in package.json are.

**Comment by NodeGuy** [comment] 2017-01-04 21:47
Actually to my great dismay it doesn't provide that for the users of packages, only the developers.

https://medium.com/@boennemann/avoid-yarn-for-packages-and-fully-enjoy-its-benefits-for-application-development-8bdd4deb33cf#.q21sj07pb

**Comment by jokeyrhyme** [comment] 2017-01-05 00:50
NPM 5.x is being discussed and designed now, and part of this likely includes a solid specification for how `npm shrinkwrap` is supposed to function:

http://blog.npmjs.org/post/154473364440/npm5-specifications-and-our-rfc-process

**Comment by NodeGuy** [comment] 2017-01-05 23:25
Cool!

**Comment by HenrikJoreteg** [comment] 2020-02-18 14:13
closing due to age and package-lock pretty well covers this now, i think.

**Closed by HenrikJoreteg** 2020-02-18 14:13 UTC
